"""Initial migration.

Revision ID: 2c6e0887c286
Revises: 
Create Date: 2021-05-14 00:56:39.248607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6e0887c286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_type',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_type_name'), 'equipment_type', ['name'], unique=True)
    op.create_table('model_base',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.create_table('region',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_name'), 'region', ['name'], unique=True)
    op.create_table('school',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_type', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('_email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user__email'), 'user', ['_email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('office_phone_number', sa.Integer(), nullable=True),
    sa.Column('staff_card_photo', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_office_phone_number'), 'teacher', ['office_phone_number'], unique=False)
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('equipment_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('not_chosen_for_donate', 'selected_for_donate', 'pending_for_donate', 'donate_successful', name='equipmentstatusenum'), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_email', sa.String(length=100), nullable=True),
    sa.Column('student_card_photo', sa.String(length=200), nullable=True),
    sa.Column('face_index', sa.String(length=200), nullable=True),
    sa.Column('user_photo', sa.String(length=150), nullable=True),
    sa.Column('about_me', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.FLOAT(precision=32), nullable=True),
    sa.Column('longitude', sa.FLOAT(precision=32), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('not_activated', 'student_activated_wait_for_teacher_approval', 'student_not_activated_and_teacher_approved', 'activated', name='studentstatusenum'), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location', 'student', ['latitude', 'longitude'], unique=False)
    op.create_table('equipment_application',
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.FLOAT(precision=32), nullable=True),
    sa.Column('longitude', sa.FLOAT(precision=32), nullable=True),
    sa.Column('address', sa.String(length=220), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('waiting_for_teacher_approval', 'teacher_approved', 'teacher_rejected', 'waiting_for_donation', 'confirming_donation', 'donation_complete', name='equipmentapplicationstatusenum'), nullable=True),
    sa.Column('home_photo', sa.String(length=200), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('thanks_photo', sa.String(length=200), nullable=True),
    sa.Column('thanks_message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repair_application',
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.FLOAT(precision=32), nullable=True),
    sa.Column('longitude', sa.FLOAT(precision=32), nullable=True),
    sa.Column('address', sa.String(length=220), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('status', sa.Enum('pending', 'repairing', 'repaired', name='repairapplicationstatusenum'), nullable=True),
    sa.Column('repair_photo', sa.String(length=200), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('thanks_photo', sa.String(length=200), nullable=True),
    sa.Column('thanks_message', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('title_zh_Hant', sa.String(length=100), nullable=True),
    sa.Column('title_en', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_zh_Hant', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_urgency'), 'story', ['urgency'], unique=False)
    op.create_table('message',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=240), nullable=True),
    sa.Column('equipment_application_id', sa.Integer(), nullable=True),
    sa.Column('repair_application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_application_id'], ['equipment_application.id'], ),
    sa.ForeignKeyConstraint(['repair_application_id'], ['repair_application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_index(op.f('ix_story_urgency'), table_name='story')
    op.drop_table('story')
    op.drop_table('repair_application')
    op.drop_table('equipment_application')
    op.drop_index('idx_location', table_name='student')
    op.drop_table('student')
    op.drop_table('equipment')
    op.drop_table('volunteer')
    op.drop_index(op.f('ix_teacher_office_phone_number'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_table('donor')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user__email'), table_name='user')
    op.drop_table('user')
    op.drop_table('school')
    op.drop_index(op.f('ix_region_name'), table_name='region')
    op.drop_table('region')
    op.drop_table('model_base')
    op.drop_index(op.f('ix_equipment_type_name'), table_name='equipment_type')
    op.drop_table('equipment_type')
    # ### end Alembic commands ###
